project:
  type: website

website:
  title: "Patterson Prayer Friends"
  navbar:
    right:
      - about.qmd
      - icon: envelope
        href: mailto:stewart.j.patterson@gmail.com
      - icon: piggy-bank-fill
        href: https://www.sunriseinternational.org/financial-support/
      - icon: facebook
        href: https://www.facebook.com/stew.patterson
      - icon: linkedin
        href: https://www.linkedin.com/in/stewart-patterson-4ab19781/
      - icon: github
        href: https://github.com/
      - icon: rss
        href: index.xml
        
  open-graph: true

format:
  html:
    # title-block-banner: profile.jpg
    theme: 
      light: cerulean
      dark: slate
    css: styles.css

editor: visual

margin-header: subscribe.html # Email subscription widget

site-url: https://pattersonsinjapan.com/
description: "Patterson Prayer Friends"
